language: objective-c
osx_image: xcode7.3
xcode_scheme: Bit
before_install:
- gem install cocoapods -v '= 1.0.0'
- gem install xcpretty --no-document
script:
- set -o pipefail # required to let xcpretty use the same exit code like xcodebuild
- xcodebuild -project Bit.xcodeproj -scheme "Bit" -destination name="iPhone 6" -destination name="iPhone 6" test | xcpretty -c
- pod lib lint --quick # lint podspec
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'Bit' # Code coverage
